export const cursos = [
  {
    id: 1,
    title: "Curso HTML5",
    text: "el lenguaje estándar para la creación y diseño de páginas web. Permite estructurar el contenido de una página web",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630705/icons/we6m6jdr2strcxqmfiq9.png",
    link: "https://www.youtube.com/watch?v=kN1XP-Bef7w&list=PLE8uP447fYpgOwKgbypiCGSz7veY2MLGb&index=1",
    docs: "https://developer.mozilla.org/es/docs/Web/HTML",
    name: "html",
    autor: "SoyDalto",
  },
  {
    id: 2,
    title: "Node.js",
    text: "Un entorno de ejecución de JavaScript del lado del servidor. Se utiliza para construir aplicaciones web escalables y en tiempo real.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630708/icons/brjr91fo2bz5nkp8qzfa.png",
    link: "https://youtube.com/playlist?list=PLUofhDIg_38qm2oPOV-IRTTEKyrVBBaU7&si=_VI_r3u8jC6AaZjV",
    docs: "https://nodejs.org/en",
    name: "node",
    autor: "Midudev",
  },
  {
    id: 3,
    title: "React",
    text: "Una biblioteca de JavaScript para construir interfaces de usuario interactivas y reutilizables.Es útil para la creación de aplicaciones de una sola página",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630710/icons/knr3vzwcdbhbm1m2vjkx.png",
    link: "https://www.youtube.com/playlist?list=PLUofhDIg_38q4D0xNWp7FEHOTcZhjWJ29",
    docs: "https://react.dev/",
    name: "react",
    autor: "Midudev",
  },
  {
    id: 4,
    title: "JavaScript",
    text: "Un lenguaje de programación del lado del cliente que se utiliza para agregar interactividad y dinamismo a las páginas web.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630706/icons/axdfl44xs4xjq9c2nkxj.png",
    link: "https://www.youtube.com/playlist?list=PLE8uP447fYpiBqMVF1hdWl9uFeVEeXRTm",
    docs: "https://developer.mozilla.org/es/docs/Web/JavaScript",
    name: "javascript",
    autor: "SoyDalto",
  },
  {
    id: 5,
    title: "SQL",
    text: " Un lenguaje estándar para gestionar bases de datos relacionales. Se utiliza para realizar consultas, actualizaciones y modificaciones en bases de datos.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630710/icons/eboqm8wgoemsocki1uay.png",
    link: "https://www.youtube.com/watch?v=DFg1V-rO6Pg&t=18s",
    docs: "https://sqlbolt.com/",
    name: "sql",
    autor: "SoyDalto",
  },
  {
    id: 6,
    title: "MySQL",
    text: "Un sistema de gestión de bases de datos relacional (RDBMS) que utiliza SQL. Es ampliamente utilizado para almacenar y gestionar datos.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630707/icons/vy1vp6znf6o6bnezxek8.png",
    link: "https://youtu.be/96s2i-H7e0w?si=s07_R_DmBjE2OKWV",
    docs: "https://www.mysql.com/",
    name: "mysql",
    autor: "Midudev",
  },
  {
    id: 7,
    title: "Curso CSS3",
    text: "Se utiliza para dar estilo y formato al contenido HTML. Controla el diseño, la presentación y la apariencia visual de una página web.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630703/icons/qdfgu9p4itbgr9lurdow.png",
    link: "https://www.youtube.com/watch?v=OWKXEJN67FE",
    docs: "https://developer.mozilla.org/es/docs/Web/css",
    name: "css",
    autor: "SoyDalto",
  },
  {
    id: 8,
    title: "MongoDB",
    text: "Una base de datos NoSQL que utiliza documentos JSON para almacenar datos. Es especialmente eficaz para manejar grandes cantidades de datos no estructurados.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630707/icons/vy1vp6znf6o6bnezxek8.png",
    link: "https://youtu.be/HsYA3QvWGlk?si=wab3gUduLcaVR7y3",
    docs: "https://www.mongodb.com/es",
    name: "mongodb",
    autor: "Midudev",
  },
  {
    id: 9,
    title: "Deno",
    text: "Un entorno de ejecución de JavaScript y TypeScript del lado del servidor, creado como alternativa a Node.js, con un enfoque en la seguridad y la simplicidad.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630703/icons/xrovcursustm3d3eu8pk.png",
    link: "https://youtu.be/KsgDQL6jj2M?si=bA_XB7TxOr6Yi3ZN",
    docs: "https://deno.com/",
    name: "deno",
    autor: "Midudev",
  },
  {
    id: 10,
    title: "Next.js",
    text: "Un marco de desarrollo para React que facilita la creación de aplicaciones web con renderización del lado del servidor (SSR) y generación de páginas estáticas.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715640770/icons/jb2uqrihkaabidaimxfu.svg",
    link: "https://youtu.be/_SPoSMmN3ZU?si=-vH2iwQXr8hise6Y",
    docs: "https://nextjs.org/",
    name: "next",
    autor: "fazt",
  },
  {
    id: 11,
    title: "Bun",
    text: "Un compilador de JavaScript y TypeScript que permite crear aplicaciones web más eficientes y rápidas al reducir el tamaño del código.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630703/icons/hmprf0j4mshkrpkvooqo.svg",
    link: "https://youtu.be/9gM7HQ7SafE?si=M4CmXRkQfOSNI7hE",
    docs: "https://bun.sh/",
    name: "bun",
    autor: "Fazt",
  },
  {
    id: 12,
    title: "Astro",
    text: "Un marco de desarrollo para la construcción de sitios web que utiliza una arquitectura de renderizado por demanda y permite la creación de sitios estáticos y dinámicos.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630702/icons/kflghtvuthksuvjnoksh.svg",
    link: "https://youtu.be/sOXW0ZnJxbQ?si=Bg4DXRF0ET3MGTVb",
    docs: "https://astro.build/",
    name: "astro",
    autor: "Fazt",
  },
  {
    id: 13,
    title: "Git",
    text: "Un sistema de control de versiones distribuido que permite gestionar el historial de cambios en el código fuente de un proyecto de manera colaborativa.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630704/icons/qvuhua3th3lugpyg8ral.png",
    link: "https://youtu.be/HiXLkL42tMU?si=tZBlh7VsDdpPdY-9",
    docs: "https://git-scm.com/",
    name: "git",
    autor: "Fazt",
  },
  {
    id: 14,
    title: "Express",
    text: "Un marco de desarrollo de Node.js que simplifica la creación de aplicaciones web y API mediante la definición de rutas y middleware.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630704/icons/hsymwfbrpy1cnv9suput.png",
    link: "https://youtu.be/JmJ1WUoUIK4?si=lr_1hhpVmlc3Sh80",
    docs: "https://expressjs.com/",
    name: "express",
    autor: "Fazt",
  },
  {
    id: 15,
    title: "PostgreSQL",
    text: "Un sistema de gestión de bases de datos relacional que es potente, extensible y de código abierto",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630709/icons/zvsye9kcyksg6as6yyfd.png",
    link: "https://youtube.com/playlist?list=PLgqdACsQ8US2DCzQVrdZDZCTtTFHMY0as&si=5VvoDca6cM8CXlkA",
    docs: "https://www.postgresql.org/",
    name: "postgresql",
    autor: "Victor Ramos",
  },
  {
    id: 16,
    title: "TypeScript",
    text: "Una extensión de JavaScript que agrega tipos estáticos opcionales. Facilita el desarrollo de código más robusto y mantenible.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630711/icons/ay8gq45jhpfyisvyykbp.png",
    link: "https://youtu.be/fUgxxhI_bvc?si=tQNu1u_AkDnYHMDr",
    docs: "https://www.typescriptlang.org/",
    name: "typescript",
    autor: "Midudev",
  },
  {
    id: 17,
    title: "GitHub",
    text: "Una plataforma de desarrollo colaborativo que utiliza Git para el control de versiones. Permite a los desarrolladores trabajar juntos en proyectos de software",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715640749/icons/tgtibq4acvpmnuihxrxh.svg",
    link: "https://youtu.be/3GymExBkKjE?si=A27DhKzTw4paK-2E",
    docs: "https://github.com/",
    name: "github",
    autor: "MoureDev",
  },
  {
    id: 18,
    title: "Bootstrap",
    text: "Un marco de diseño front-end que facilita el diseño y desarrollo de interfaces web responsivas y atractivas.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630702/icons/xiv0rw6r7gjphmnkqclu.png",
    link: "https://youtu.be/QCw0L6FupQ0?si=EduiMGTsgbmiD3Yz",
    docs: "https://getbootstrap.com/",
    name: "bootstrap",
    autor: "FreeCodeCamp",
  },
  {
    id: 19,
    title: "Tailwind CSS",
    text: "Un marco de diseño CSS utilitario que permite diseñar interfaces de usuario de manera eficiente y personalizada.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630711/icons/z0e8iw2eztq6xbx9hltf.png",
    link: "https://youtube.com/playlist?list=PLPl81lqbj-4JdoHDiERR2ptkw9zRggXAL&si=aig-uAbEL6BzymH7",
    docs: "https://tailwindcss.com/",
    name: "tailwind",
    autor: "Bluuweb",
  },
  {
    id: 20,
    title: "Java",
    text: "Java es un lenguaje de programación que se utiliza ampliamente para desarrollar aplicaciones empresariales, aplicaciones móviles, juegos y aplicaciones web.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630706/icons/q5rsrd9k6wpwkgn9ndev.png",
    link: "https://youtu.be/Bi9AmOBDJGY?si=MVNyP1spIy2AVdQr",
    docs: "https://www.java.com/es/",
    name: "java",
    autor: "Programación Fácil",
  },
  {
    id: 21,
    title: "Python",
    text: "Python es un lenguaje de programación que se utiliza en desarrollo web, análisis de datos, inteligencia artificial, desarrollo de juegos y automatización de tareas.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630709/icons/gr2igynzi7ssk4sf8d4v.png",
    link: "https://youtu.be/nKPbfIU442g?si=LxbUYsimholvoxkX",
    docs: "https://www.python.org/",
    name: "python",
    autor: "Soy dalto",
  },
  {
    id: 22,
    title: "Docker",
    text: "Docker es una plataforma que se utiliza para desarrollar, empaquetar y ejecutar aplicaciones en contenedores.Lo que facilita la implementación de aplicaciones en cualquier entorno ",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630703/icons/nxij8lksaprz4po1uuwe.png",
    link: "https://youtu.be/4Dko5W96WHg?si=VMbQMQTh10P6-Q9h",
    docs: "https://www.docker.com/",
    name: "docker",
    autor: "HolaMundo",
  },
  {
    id: 23,
    title: "Webpack",
    text: "Webpack construye módulos o paquetes que se utilizan para agrupar y empacar archivos de JavaScript, CSS, imágenes, etc.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630702/icons/sea1z0dcvjbawxlmszed.png",
    link: "https://youtu.be/FMNuTj89RzU?si=y7uhOprYWCewg3W7",
    docs: "https://webpack.js.org/",
    name: "webpack",
    autor: "Midudev",
  },
  {
    id: 24,
    title: "Angular",
    text: "Angular es un framework web que se utiliza para construir aplicaciones web de una sola página y aplicaciones web escalables.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715630702/icons/huygfslzio3twbiwxc9x.png",
    link: "https://www.youtube.com/playlist?list=PLCKuOXG0bPi0Ym-wA_VIViDzUCgPqWhWu",
    docs: "https://angular.io/",
    name: "angular",
    autor: "Fernando Herrera",
  },
  ,
  {
    id: 25,
    title: "Bash",
    text: "Un intérprete de comandos y un lenguaje de scripting para sistemas operativos tipo Unix. Es utilizado principalmente en sistemas Linux y macOS.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/vel8f8gpreqnogwupcxj.svg",
    link: "https://youtu.be/H4ayPYcZEfI?si=Z73qisLrp2Qa2tB1",
    docs: "https://linuxconfig.org/?s=bash",
    name: "bash",
    autor: "Fazt",
  }
  ,
  {
    id: 26,
    title: "Github Actions",
    text: "Una característica de GitHub que permite automatizar flujos de trabajo en tus repositorios. Puedes crear, probar y desplegar tu código directamente desde GitHub",
    icon: "",
    link: "https://youtu.be/pNtcTmCiXzw?si=UCKSFgvr5FcSFZqI",
    docs: "https://github.com/features/actions",
    name: "github actions",
    autor: "Mouredev",
  }
  ,
  {
    id: 27,
    title: "Nest.js",
    text: "Un framework de Node.js para construir aplicaciones escalables y eficientes en el servidor",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/qynbkeqjxl6lkcnmeipp.svg",
    link: "https://youtu.be/wsqcg5ZtUMM?si=BSskH4AjqdU-7Vo1",
    docs: "https://nestjs.com/",
    name: "nest",
    autor: "Fazt",
  }
  ,
  {
    id: 28,
    title: "php",
    text: "Un lenguaje de programación ampliamente utilizado, especialmente para el desarrollo web del lado del servidor",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/vo7awerkx1q6awaka5j9.svg",
    link: "https://youtu.be/BcGAPkjt_IE?si=lssfKibUpjJffLTq",
    docs: "https://www.php.net/",
    name: "php",
    autor: "Midudev",
  }
  ,
  {
    id: 29,
    title: "Prisma",
    text: "Una herramienta de mapeo de objetos relacionales (ORM) para bases de datos en TypeScript y JavaScript",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/one8ytnl0ckt9uryraw5.svg",
    link: "https://youtu.be/N5dkg28jRF0?si=strXpsWmfEQsLxK5",
    docs: "https://www.prisma.io/",
    name: "prisma",
    autor: "Fazt",
  }
  ,
  {
    id: 30,
    title: "Programación",
    text: "Es el proceso de formular algoritmos para resolver problemas. Es fundamental en el desarrollo de software.",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637705/icons/bgvuewrhovfzraod7qim.png",
    link: "https://youtube.com/playlist?list=PLyvsggKtwbLVva0XXvoqx91iaLmhgeNy7&si=CQPv5WRuKRIfs2Vz",
    docs: "https://software1278.webnode.es/blog/conceptos-basicos-de-logica-de-programacion-/",
    name: "logica",
    autor: "La geekipedia de Ernesto",
  }
  ,
  {
    id: 31,
    title: "Visual Studio Code",
    text: "Un popular editor de código fuente desarrollado por Microsoft. Es altamente personalizable y cuenta con una amplia gama de extensiones",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/unjac5xuc5e5nuw3hgeb.svg",
    link: "https://youtu.be/TbzrOz8HbFM?si=PGCh6vcLC3hWDAYN",
    docs: "https://code.visualstudio.com/",
    name: "vs code",
    autor: "Soydalto",
  }
  ,
  {
    id: 32,
    title: "Vue",
    text: "Un popular framework de JavaScript para construir interfaces de usuario interactivas",
    icon: "https://res.cloudinary.com/duyiov4s1/image/upload/v1715637703/icons/fefrvosm8k8ckk1rmsjf.svg",
    link: "https://youtube.com/playlist?list=PLDllzmccetSNgykILXnHMeuO-y-gRcF-i&si=zMRJ7EQiqbDYmrr3",
    docs: "https://vuejs.org/",
    name: "vue",
    autor: "GOGODEV",
  }
];
